#!/usr/bin/env python3
"""Regenerate assets/glossary-data.js from glossary.html.
Run from the repo root whenever a term is added or a definition changes:
    python3 tools/build-glossary.py
Each <dt id="slug">Term</dt><dd>definition</dd> pair becomes GLOSSARY[slug] = {t, d, a}.
Aliases (other spellings the tooltip matcher should catch) live in ALIASES below."""
import re, html, json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "glossary.html").read_text(encoding="utf-8")
ALIASES = {
    # slug: [other forms found in running text]. A "/"-separated term is split automatically.
    "candy-cab": ["candy cabinet", "candy cabs"],
    "bkm": ["BKM cards", "BKM slot", "BKM slots", "BKM input card", "BKM input cards"],
    "tvl": ["TV lines", "lines of resolution"],
    "scanlines": ["scanline"],
    "cocktail": ["cocktail cabinet"],
    "cps": ["CPS1", "CPS2", "CPS-1", "CPS-2"],
    "playchoice-10": ["PC-10", "PlayChoice"],
    "breakout": ["breakout cable", "SCART to 4 BNC"],
    "scaler": ["line doubler", "upscaler"],
    "distribution-amp": ["distribution amp"],
    "instruction-card": ["instruction cards"],
    "rgb-mod": ["RGB mods", "RGB-modded", "RGB modded"],
    "aperture-grille": ["aperture-grille"],
    "geometry": ["convergence"],
    "zero-scan": ["underscan"],
    "backglass": ["translite"],
    "huo": ["home use only"],
    "nos": ["new old stock"],
    "audio-monitor": ["audio monitors"],
    "trinitron": ["Trinitrons"],
    "switcher": ["auto-switcher"],
}
# terms too generic to auto-underline in prose (they still exist on glossary.html)
SKIP = {"upright", "dedicated", "conversion", "kit", "monitor", "chassis", "cabinet", "marquee", "bezel", "topper", "shop-out", "sync", "route"}
out = {}
for m in re.finditer(r'<dt id="([^"]+)">(.*?)</dt>\s*<dd>(.*?)</dd>', src, re.S):
    slug, term, d = m.group(1), m.group(2), m.group(3)
    term = re.sub(r"<small>.*?</small>", "", term, flags=re.S)  # "CPO <small>control panel overlay</small>" → "CPO"
    term = html.unescape(re.sub(r"<[^>]+>", "", term)).strip()
    parts = [t.strip() for t in term.split(" / ") if t.strip()]
    term, extra = parts[0], parts[1:]
    d = re.sub(r"\s+", " ", d).strip()
    # keep inline links out of the tooltip: plain text, entities preserved for safety
    d = re.sub(r"<[^>]+>", "", d)
    if slug in SKIP:
        continue
    out[slug] = {"t": term, "d": d, "a": extra + ALIASES.get(slug, [])}
js = "// Generated by tools/build-glossary.py from glossary.html — do not edit by hand.\nconst GLOSSARY = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n"
(root / "assets" / "glossary-data.js").write_text(js, encoding="utf-8")
print(f"{len(out)} terms → assets/glossary-data.js")
